# <font color='orangered'>Error Handling in Python, Functions and NumPy</font>

***
**`Through the session, we will cover the following topics:`**
* [x] **Functions** - Creation user define function, how use user define function, buildin function and how to use them.
* [x] **Error Handling** - Handling error in codes.
* [x] **Numpy** - What is Numeric Python and when we need to use it.

# Function

- A function is a block of organized, reusable code that is used to perform a single, related action. Functions provide better modularity for your application and a high degree of code reusing.
- Functions help break our program into smaller and modular chunks. As our program grows larger and larger, functions make it more organized and manageable.

## Defining a Function

- You can define functions to provide the required functionality. Here are simple rules to define a function in Python.
    * Function blocks begin with the keyword `def` followed by the function name and parentheses ( ( ) ).
    * Any input parameters or arguments should be placed within these parentheses. You can also define parameters inside these parentheses.
    * The first statement of a function can be an optional statement - the documentation string of the function or docstring.
    * The code block within every function starts with a `colon (:)` and is indented.
    * The statement return exits a function, optionally passing back an expression to the caller. A return statement with no arguments is the same as return None.

**Syntax**
```
def functionname( parameters ):
   "function_docstring"
   function_suite
   return [expression]
```

In [ ]:
# Area of a circle ? - Formula - dependent on radius , radius becomes a variable input
# Does the formula depend on Pi ? Constant -
def area(r): # r is a necessary variable the function needs, there are other default variables also possible
    area_of_circle = 3.14*r*r # Local variable - which has it's scope only inside the function
    print(f"The area is {area_of_circle:.0f}")

## Calling a Function

- Defining a function only gives it a name, specifies the parameters that are to be included in the function and structures the blocks of code.
- Once the basic structure of a function is finalized, you can execute it by calling it from another function or directly from the Python prompt.

In [ ]:
area(10) # Use the output elsewhere - save it in a variable

The area is 314


## The return Statement

- The statement return [expression] exits a function, optionally passing back an expression to the caller. A return statement with no arguments is the same as return None.

In [ ]:
def summation(a,b):
    total=a+b
    print("The Sum of the values is ",total)
    return total

In [ ]:
summation(10,20)

The Sum of the values is  30


30

## Function Arguments

- You can call a function by using the following types of formal arguments −
    * Required arguments
    * Keyword arguments
    * Default arguments
    * Variable-length arguments

### Required arguments

- Required arguments are the arguments passed to a function in correct positional order. Here, the number of arguments in the function call should match exactly with the function definition.

In [ ]:
def reqfunction(a):
    print(a)
    return

In [ ]:
# Calling the function
reqfunction()

TypeError: reqfunction() missing 1 required positional argument: 'a'

### Keyword arguments

- Keyword arguments are related to the function calls. When you use keyword arguments in a function call, the caller identifies the arguments by the parameter name.
- This allows you to skip arguments or place them out of order because the Python interpreter is able to use the keywords provided to match the values with parameters.

In [ ]:
def keyfunction(a):
    print(a)
    return

In [ ]:
keyfunction(a="a")

a


In [ ]:
def keyfunction_1(a,b):
    print("The Value of a is",a)
    print("The Value of b is",b)
    return

In [ ]:
keyfunction_1(a=10,b=20) # Keyword Arguments
keyfunction_1(10,20)

The Value of a is 10
The Value of b is 20


In [ ]:
keyfunction_1(10,20)

The Value of a is 10
The Value of b is 20


In [ ]:
keyfunction_1(20,10)

The Value of a is 20
The Value of b is 10


In [ ]:
keyfunction_1(b=10,a=20)

The Value of a is 20
The Value of b is 10


### Default arguments

- A default argument is an argument that assumes a default value if a value is not provided in the function call for that argument.

In [ ]:
def deffunction(a,b=20):
    print("The Value of a is",a)
    print("The Value of b is",b)

In [ ]:
deffunction(10,20)

The Value of a is 10
The Value of b is 20


In [ ]:
deffunction(10)

The Value of a is 10
The Value of b is 20


#### Calling a Function without an Argument
- The variable specified within the parentheses in the function declaration is referred to as a parameter. When a function is called, an argument is the value that is sent to it.
- In Python, parameters are variables that serve as placeholders for the values that the function requires. These values are handed in as parameters when the function is invoked. The parameters supplied into the function

In [ ]:
def argfunc():
    a=0
    for i in range(10):
        a+=i
    return a

In [ ]:
argfunc()

45

#### Calling a Function with Default Argument
- We can define the value of the arguments in the function definition and call the function without supplying any argument to get the default result. But we can also call such functions by supplying new values of the argument and get non default result.

In [ ]:
def multiply(a=3,b=4):
    return a*b

In [ ]:
multiply()

12

### Variable-length arguments

- You may need to process a function for more arguments than you specified while defining the function. These arguments are called variable-length arguments and are not named in the function definition, unlike required and default arguments.

In [ ]:
def mean(*a):

    mean = sum(a) / len(a)
    return mean

In [ ]:
mean(1,2,3,4,5,6,7,8,9)

5.0

In [ ]:
def varlfunction(a,*b):
    a=a
    for i in b:
        a+=i
    return a

In [ ]:
varlfunction(10,20,30,40)

100

* An asterisk (*) is placed before the variable name that holds the values of all nonkeyword variable arguments. This variable remains empty if no additional arguments are specified during the function call.

In [ ]:
varlfunction(10)

10

## Exercise :
- Write a function with 2 required arguments from user
    1. Profession
    2. Age
    3. 1 default argument - Country - India
- Print on the screen - I am a {age} year old {profession} coming from {country}

## Scope of Variables

- All variables in a program may not be accessible at all locations in that program. This depends on where you have declared a variable.
- The scope of a variable determines the portion of the program where you can access a particular identifier. There are two basic scopes of variables in Python −
    * Global variables
    * Local variables

In [ ]:
def my_func(a = 10 ) :
    b = 8
    return a+b

In [ ]:
b = 10 # global variable

In [ ]:
my_func()

18

In [ ]:
b

10

In [ ]:
# Every function - first searches in its local scope
# If the value is found, it uses it, if not found -
# It searches again in global scope, finds it - uses it
# If not found again - error

In [ ]:
def my_func(a = 10 ) :
    return a+b

In [ ]:
my_func()

15

In [ ]:
def my_func(a = 10 ) :
    total_value = a+b # Local scope within the function, it is not existent outside the function

    return total_value

In [ ]:
my_func()

15

In [ ]:
print(total_value)

NameError: name 'total_value' is not defined

### Global vs. Local variables

- Variables that are defined inside a function body have a local scope, and those defined outside have a global scope.
- This means that local variables can be accessed only inside the function in which they are declared, whereas global variables can be accessed throughout the program body by all functions. When you call a function, the variables declared inside it are brought into scope. Following is a simple example −

In [ ]:
total = 0 # This is global variable.

# Function definition is here
def sumfunc( a,b):
   # Add both the parameters and return them."
    total = a+b; # Here total is local variable.
    print("Inside the function local total : ", total)
    return total

# Now you can call sum function
sumfunc(10,20)
print("Outside the function global total : ", total)

Inside the function local total :  30
Outside the function global total :  0


In [ ]:
# Build a function that takes the names of students from the students_list
# And returns the short forms of the names
students = ["Abdur Rahaman" , "Abhinav Srivastava" , "Akansha" , "Arya Bondale" , "Asim Bisayee"]
initials = ["AR" , "AS" , "A" , "AB" , "AB"]

In [ ]:
def short_form(student):
    output=[]
    for name in student:
        f_l_name = name.split(" ")
        ini = []
        for i in f_l_name:
            ini.append(i[0])
        output.append("".join(ini))
    return output

In [ ]:
short_form(students)

['AR', 'AS', 'A', 'AB', 'AB']

## Nested Functions

- Thus far, to perform any specific task, we have executed every function separately, if we wanted to use the results of a function for downstream purposes, we saved the results to a variable. As you become more comfortable with Python, you will find that it is more efficient to code using nested functions, or functions within other functions, which will allow you to execute multiple commands at the same time. There are two ways to create a nested function:
    * Call a function within another function.
    * Write a function within a function.

In [ ]:
# there are 2 ways we can define nesting of functions
# Nesting functions when defining them

def volume(l,b,h):

    def area(l,b):
        return l*b

    return area(l,b)*h

In [ ]:
def parent_func(a,b):

    def child_function(a):

        print(a+b)

    child_function(a)

In [ ]:
parent_func(10,20)

30


In [ ]:
child_function(10)

NameError: name 'child_function' is not defined

### Call a function within another function

- If you want to store the value in a variable to be later used somehwere in the code -
1. The function should have a return
2. The function should be called and the value should be saved in a variable

In [ ]:
def area(l,b):
    return l*b

def volume(a,h):
    return a*h

In [ ]:
output_volume = volume(area(5,4), 3)

In [ ]:
output_volume

60

### Write a function within a function

In [ ]:
def outer():  # outer function
    print("This is outer function")
    def inner():
        print("This is inner function")
    inner()  # calling inner function inside outer function

In [ ]:
outer()  # calling outer function

This is outer function
This is inner function


- We defined a function named inner() inside another function named outer(). Thus, inner() is a nested function.
- When the outer() function is called, its body is executed. Inside its body, the inner() function is defined and then called. Thus, we first called the outer() function which in turn called the inner() function.

- Note that an inner function is always called from inside the function in which it is defined. Thus, to call the inner function, we need to call the outer function.
- A nested function can access the variables defined in the function in which it is created. This is demonstrated in the following example.

In [ ]:
def outer():  # outer function
    x = 10
    def inner():
        print("Inside inner func", x)
    inner()  # calling inner function inside outer function
    print("Inside outer func", x)

In [ ]:
outer()  # calling outer function

Inside inner func 10
Inside outer func 10


## Exercise :
1. Write a program to calculate the final price of a product after applying a discount and tax using nested functions.
2. Define an outer function `calculate_price(base_price, discount_percentage, tax_percentage)` that:
   - Takes three arguments:
     - `base_price` (float) for the product price before discounts and taxes.
     - `discount_percentage` (float) for the percentage discount to apply.
     - `tax_percentage` (float) for the percentage tax to apply.
   - Defines two inner functions:
     - `apply_discount(price, discount)` that calculates and returns the price after the discount.
     - `apply_tax(price, tax)` that calculates and returns the price after adding tax.
   - Calls the inner functions in sequence to first apply the discount and then apply the tax.
   - Returns the final price.

3. Call the `calculate_price` function with sample values and print the result.

### Example Input/Output:
```
Input:
   base_price = 100.0
   discount_percentage = 10.0
   tax_percentage = 5.0
   calculate_price(base_price, discount_percentage, tax_percentage)

Output:
  $94.50



## Recursive Function

- In Python it is used for repetitively calling the same function until the loop reaches the desired value during the program execution by using the divide and conquer logic. One of the obvious disadvantages of using a recursive function in the Python program is ‘if the recurrence is not a controlled flow, it might lead to consumption of a solid portion of system memory. For rectifying this problem, an incremental conditional loop can be used in place of the Recursive function in a python programming language.

```
The concept of recursion remains the same in Python. The function calls itself to break down the problem into smaller problems. The simplest example we could think of recursion would be finding the factorial of a number.

Let’s say we need to find the factorial of number 5 => 5! (Our problem)
To find 5! the problem can be broken into smaller ones 5! => 5 x 4!
So, to get 5! We need to find 4! and multiply it with 5.
Let’s keep on dividing the problem
5! = 4! x 5
4! = 3! x 4
3! = 3 x 2!
2! = 2 x 1!
1! = 1
When it reaches the smallest chunk, i.e., getting the factorial of 1, we can return the result as
```

In [ ]:
def factorial(n):

    # recursive function - define a stopping criteria - non recursive
    if n==2:
        return 2 # NOT call the function itself
    else:
        return n*factorial(n-1)

In [ ]:
factorial(5)

120

```
get_factorial(5)                    # 1st call with 5
5 * get_factorial(4)                # 2nd call with 4
5 * 4 * get_factorial(3)            # 3rd call with 3
5 * 4 * 3 * get_factorial(2)        # 4th call with 2
5 * 4 * 3 * 2                       # return from 5th call as n=1
5 * 4 * 6                           # return from 3rd call
5 * 24                              # return from 2nd call
120                                 # return from 1st call
```

# Error Handling in Python

***Why Do We Need Error Handling?***

* **Prevents program from crashing if an error occurs**
    - If an error occurs in a program, we don’t want the program to unexpectedly crash on the user. Instead, error handling can be used to notify the user of why the error occurred and gracefully exit the process that caused the error.
* **Saves time debugging errors**
    - Following reason #1, having the program display an error instead of immediately crashing will save a lot of time when debugging errors. The logic inside the error handler can be updated to display useful information for the developer, such as the code trackback, type of error, etc.
* **Helps define requirements for the program**
    - If the program crashes due to bad input, the error handler could notify the user of why the error occurred and define the requirements and constraints of the program.

- Python Try Except
    * The try block lets you test a block of code for errors.
    * The except block lets you handle the error.
    * The else block lets you execute code when there is no error.
    * The finally block lets you execute code, regardless of the result of the try- and except blocks.

- Exception Handling
    * When an error occurs, or exception as we call it, Python will normally stop and generate an error message.
    * These exceptions can be handled using the try statement:

In [ ]:
try:
    # Usual flow of the code

except:

    # What to do if there is an exception

In [ ]:
print(x)

NameError: name 'x' is not defined

In [ ]:
# The try block will generate an exception, because x is not defined
try:
    print(x) # Your actual code - this will run smoothly, if everything is fine
except: # Exception / Error
    print("An exception occurred") # This is the action to take

An exception occurred


In [ ]:
1/ 0

ZeroDivisionError: division by zero

In [ ]:
'a' + 2

TypeError: can only concatenate str (not "int") to str

- Since the try block raises an error, the except block will be executed.
- Without the try block, the program will crash and raise an error:

In [ ]:
print(x)

NameError: name 'x' is not defined

### Many Exceptions

- You can define as many exception blocks as you want, e.g. if you want to execute a special block of code for a special kind of error:

In [ ]:
try:
    print(x)
except NameError:
    print("Variable x is not defined")
except:
    print("Something else went wrong")

Variable x is not defined


### Else
- You can use the else keyword to define a block of code to be executed if no errors were raised:

In [ ]:
try:
    print("Hello")
except:
    print("Something went wrong")
else:
    print("Nothing went wrong")

Hello
Nothing went wrong


### Finally
- The finally block, if specified, will be executed regardless if the try block raises an error or not.

In [ ]:
try:
    print(x)
except:
    print("Something went wrong")
finally:
    # close connection
    print("The 'try except' is finished")

5
The 'try except' is finished


- This can be useful to close objects and clean up resources.

In [ ]:
# Try to open and write to a file that is not writable
try:
    f = open("demofile.txt","a")
    try:
        f.write("Lorum Ipsum")
    except:
        print("Something went wrong when writing to the file")
    finally:
        f.close()
except:
    print("Something went wrong when opening the file")

- The program can continue, without leaving the file object open.

In [ ]:
# USER DEFINED EXCEPTIONS

In [ ]:
age = int(input("Enter your age"))

if age < 0 :
    raise Exception("Age cannot be negative")

Enter your age -30


Exception: Age cannot be negative

### Raise an exception
- As a Python developer you can choose to throw an exception if a condition occurs.
- To throw (or raise) an exception, use the raise keyword.

In [ ]:
age_input = int(input("Enter age : "))

if age_input < 0: # Logical errors specific to your usecase
    raise Exception("Age cannot be negative")

Enter age :  -10


Exception: Age cannot be negative

- The raise keyword is used to raise an exception.
- You can define what kind of error to raise, and the text to print to the user.

In [ ]:
# Raise a TypeError if x is not an integer
x = "hello"

if not type(x) is int:
    raise TypeError("Only integers are allowed")

TypeError: Only integers are allowed

In [ ]:
# 3 fundamental parts of programming

# 1. Data Types and Handling Them using methods, functions etc
# 2. Conditonal Statements - if , elif , else
# 3. Repetitive Execution - Loops, For , While -> Break, continue, Pass, error handling

# Functions

In [ ]:
# you are the first astronomer who is using Python for some processes and tasks
# you've written some code to solve complex problems

# Open Source -> Share your code with the world and everyone can use it freely

# Exercise:

Write a Python program that continuously prompts the user to enter a password. The program should:

1. Compare the entered password with a predefined correct password.
2. If the password matches:
   - Print `"Access Granted!"`
   - Exit the loop and terminate the program.
3. If the password does not match:
   - Print an error message: `"Incorrect password. Please try again."`
   - Continue prompting the user to enter the password.
4. Ensure the program handles unexpected input gracefully, such as:
   - Empty passwords.
   - Non-string input.

# NumPy

- NumPy stands for Numerical Python.
- NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.
- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

**Why Use NumPy?**

- In Python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
- Arrays are very frequently used in data science, where speed and resources are very important.

**Why is NumPy Faster Than Lists?**

- NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
- This behavior is called locality of reference in computer science.
- This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

## Installation of NumPy

- If you've installed Anaconda then no need to install `NumPy` it's already installed.
- If you have Python and PIP already installed on a system, then installation of NumPy is very easy.
- Install it using this command:

In [ ]:
!pip install jellyfish

You should consider upgrading via the '/Users/polymerize/Desktop/Polymerize/ml_dev/ml_dev/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [ ]:
import jellyfish as jf

## Import NumPy

- Once NumPy is installed, import it in your applications by adding the import keyword:

In [ ]:
import numpy as np

## Create a NumPy ndarray Object

- NumPy is used to work with arrays. The array object in NumPy is called ndarray.
- We can create a NumPy ndarray object by using the array() function.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


- To create an ndarray, you can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray.

In [ ]:
arr = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array({1, 2, 3, 4, 5})
print(arr)
print(type(arr))

{1, 2, 3, 4, 5}
<class 'numpy.ndarray'>


## Dimensions in Arrays

- A dimension in arrays is one level of array depth (nested arrays).

### 0-D Arrays

- 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [ ]:
arr = np.array(6)
print(arr)

6


### 1-D Arrays

- An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


### 2-D Arrays

- An array that has 1-D arrays as its elements is called a 2-D array.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


### 3-D arrays

- An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Check Number of Dimensions?

- NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [ ]:
arr_1 = np.array(6)
arr_2 = np.array([1, 2, 3, 4, 5])
arr_3 = np.array([[1, 2, 3], [4, 5, 6]])
arr_4 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr_1.ndim)
print(arr_2.ndim)
print(arr_3.ndim)
print(arr_4.ndim)

0
1
2
3


### Higher Dimensional Arrays

- An array can have any number of dimensions. When the array is created, you can define the number of dimensions by using the ndmin argument.

In [ ]:
arr = np.array([1, 2, 3], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3]]]]]
number of dimensions : 5


- In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

## Indexing & Slicing
- Contents of ndarray object can be accessed and modified by indexing or slicing, just like Python's in-built container objects. Items in ndarray object follows zero-based index. Three types of indexing methods are available − field access, basic slicing and advanced indexing.

- Basic slicing is an extension of Python's basic concept of slicing to n dimensions. A Python slice object is constructed by giving start, stop, and step parameters to the built-in slice function. This slice object is passed to the array to extract a part of array.

In [ ]:
arr = np.array([1, 2, 3, 4])
arr[0]

1

In [ ]:
arr[0:2]

array([1, 2])

**Access 2-D Arrays**

- To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element. Think of 2-D arrays like a table with rows and columns, where the row represents the dimension and the index represents the column.
Example

In [ ]:
# Access the element on the first row, second column
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('3rd element on 2nd row: ', arr[1, 2])

3rd element on 2nd row:  8


- the Same way we can access three or more dimension arrays

## Numpy Side Effects

- First of all, numpy arrays cannot contain elements with different types [Ex: Strings, Dates, Alphanumerics, Floats, Integers]
- Second, the typical arithmetic operators, such as +, -, * and / have a different meaning for regular Python lists and numpy arrays.

In [ ]:
np.array([1, 3 , 2])

array([1, 3, 2])

In [ ]:
# np.array([[1,2,3],[4,5,6],[7,8,9]]) * np.array([1,2,3])

In [ ]:
import numpy as np
np.array([True, 1, 2]) * np.array([3, 4, False])

array([3, 4, 0])

In [ ]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [ ]:
[True, 1, 2] + [3, 4, False]

[True, 1, 2, 3, 4, False]

In [ ]:
np.array([4, 3, 0]) + np.array([0, 2, 2])

array([4, 5, 2])

## Statistics with Numpy

In [ ]:
x = [1, 4, 8, 10, 12]

In [ ]:
# Mean
np.mean(x)

7.0

In [ ]:
# Median
np.median(x)

8.0

In [ ]:
# Standard Deviation
np.std(x)

4.0

In [ ]:
y = [3, 7, 10, 2, 20]